version: '3.0'
services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snappfood
    ports:
      - '56789:5432'
    volumes:
      - snappfoodinterviewdb:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '45678:6379'
volumes:
  snappfoodinterviewdb:
    driver: local
